name: C Labs CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential make gcc clang-format clang-tidy valgrind

      # 1) Проверка кодстайла
      - name: clang-format (lint)
        run: |
          files=$(git ls-files '*.c' '*.h')
          [ -z "$files" ] && exit 0
          clang-format -style=file --dry-run -Werror $files

      # 2) clang-tidy (имена/проверки)
      - name: clang-tidy (naming & checks)
        run: |
          files=$(git ls-files '*.c')
          [ -z "$files" ] && exit 0
          clang-tidy --quiet -warnings-as-errors='*' $files -- -std=c11 -Iinclude

      # 3) Сборка
      - name: Build
        run: make -j

      # 4) I/O тесты ПОД Valgrind (скрипт сам фейлит при утечках)
      - name: IO tests (Valgrind)
        run: |
          # На всякий случай убедимся, что раннер исполняемый
          [ -f tests/run_io_tests.sh ] && chmod +x tests/run_io_tests.sh || true
          make          # твой Makefile по умолчанию запускает memcheck (Valgrind)
